# Generated by Django 5.2.7 on 2025-10-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('icone', models.CharField(max_length=10, verbose_name='�cone (emoji)')),
                ('descricao', models.TextField(verbose_name='Descri��o')),
                ('pontos_necessarios', models.IntegerField(verbose_name='Pontos Necess�rios')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('localizacao', models.CharField(max_length=300, verbose_name='Localização')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Fim')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('evento', 'Evento'), ('workshop', 'Workshop')], max_length=20)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('participantes', models.IntegerField(default=0, verbose_name='Participantes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endere�o')),
                ('horario', models.CharField(max_length=100, verbose_name='Hor�rio')),
                ('distancia', models.CharField(blank=True, max_length=50, verbose_name='Dist�ncia')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('plastico', 'Pl�stico'), ('vidro', 'Vidro'), ('papel', 'Papel'), ('metal', 'Metal'), ('eletronicos', 'Eletr�nicos'), ('organico', 'Org�nico')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descri��o')),
                ('localizacao', models.CharField(max_length=300, verbose_name='Localiza��o')),
                ('status', models.CharField(choices=[('pending', 'Aguardando Curadoria'), ('approved', 'Aprovado'), ('rejected', 'Reprovado')], default='pending', max_length=10, verbose_name='Status')),
                ('feedback_curador', models.TextField(blank=True, null=True, verbose_name='Feedback do Curador')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materiais/%Y/%m')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curador', models.ForeignKey(blank=True, limit_choices_to={'tipo': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_revisados', to=settings.AUTH_USER_MODEL)),
                ('produtor', models.ForeignKey(limit_choices_to={'tipo': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='materiais_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('pontos', models.IntegerField(verbose_name='Pontos Ganhos')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('coletado', 'Coletado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('data_coleta', models.DateField(verbose_name='Data da Coleta')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='producer.material')),
            ],
            options={
                'verbose_name': 'Coleta',
                'verbose_name_plural': 'Coletas',
                'ordering': ['-data_coleta'],
            },
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usu�rio',
                'verbose_name_plural': 'Conquistas dos Usu�rios',
                'unique_together': {('usuario', 'conquista')},
            },
        ),
    ]
