# Generated by Django 5.2.7 on 2025-10-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endere�o')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (pessoas)')),
                ('horario', models.CharField(max_length=100, verbose_name='Hor�rio de Funcionamento')),
                ('descricao', models.TextField(verbose_name='Descri��o')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Dispon�vel')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('curso', 'Curso'), ('evento', 'Evento')], max_length=10, verbose_name='Tipo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espa�o F�sico',
                'verbose_name_plural': 'Espa�os F�sicos',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='T�tulo')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(verbose_name='Hor�rio de In�cio')),
                ('horario_fim', models.TimeField(verbose_name='Hor�rio de Fim')),
                ('tipo', models.CharField(choices=[('coleta', 'Coleta'), ('curso', 'Curso'), ('evento', 'Evento')], max_length=10, verbose_name='Tipo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='admin_dashboard.espacofisico')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario_inicio'],
            },
        ),
    ]
